### ISSUE TITLE
OpenWeatherMap Alerts

### ISSUE THREAD

**Issue by kwalkerk** [workingDog/OWOneCall#1]
Love this library - thank you!

Any suggestions as to how to include the "alerts" returned by OpenWeatherMapAPI?

**Comment by workingDog** [comment]
Thanks for your feedback. I didn't realised there were "alerts" in the responses.
 I'll have a look at it this/next week. Seems to be straightforward to implement.

**Comment by kwalkerk** [comment]
Thanks!  Sounds great

**Comment by workingDog** [comment]
Added `alerts` to responses and options, in the `async` branch. It would be good
 if "someone" could test this.

**Comment by workingDog** [comment]
Updated the `master` branch as well with `alerts`.

**Comment by kwalkerk** [comment]
I've tried it and it complies fine, but I get no data in the response from OpenWeatherMap.

I reverted back to the working version(no alerts) and I still get no data in the response.

However if I invoke the url from the command line I get data as expected.

Strange - will keep working on it

**Comment by workingDog** [comment]
"...I get no data in the response from OpenWeatherMap...", do you mean you get no data at all, or you don't get any alert data? Could you share the url (or just the lat,lon) that gives some data (on the command line) with an alert. I could not find any examples from OpenWeatherMap and the bulk downloads that gives an alert. In my tests (using https://github.com/workingDog/OWOneCallExample) with the updated code, I get the expected response, as before, but since there are no alerts, I cannot test getting those.

**Comment by kwalkerk** [comment]
It's working fine for me this morning.  Using this url:  "https://api.openweathermap.org/data/2.5/onecall?lat=30.212942&lon=-93.21891&units=imperial&exclude=minutely&lang=en&appid=(your secret key)	

Had to search online for a location which currently had severe weather alerts.  Found the one above(Lake Charles, La).  It will  expire at 9:30 Eastern.

I had to make the OWAlert structure conform to Hashable for my purposes.

Thanks so much for your quick response and for this terrific library!

Ken

Here's a screenshot of the still unfinished app:

![Screen Shot 2022-04-02 at 9 09 42 AM](https://user-images.githubusercontent.com/488547/161384847-c06dbe7c-1af7-4ed9-a3a9-fa43854cecca.png)

**Comment by workingDog** [comment]
I'm glad it is now working for you. I also tested the url and could finally see an alert.

I've updated the code, both `master` and `async` branches by 
adding `Identifiable` to `Weather` and `OWAlert`, so in theory, there should be no need for `Hashable`.

PS: 
remove your `appid` secret key from your comment. Also you may want to have a look at the code in my 
https://github.com/workingDog/YAWA project.

**Comment by kwalkerk** [comment]
Thanks - I'll checkout the YAWA.  Also thanks for the message about the secret key!
