### ISSUE TITLE
Corrupted Package

### ISSUE THREAD

**Issue by kwalkerk** [workingDog/OWOneCall#2]
I'm now getting a corrupted package message and cannot compile.  Also tried it with your example app and same result - corrupted package message

**Comment by workingDog** [comment]
could you try downloading/cloning the https://github.com/workingDog/OWOneCallExample and using it, after adding your key in the `ContentView`.
I am on macos 12.3, using xcode 13.3, targets ios 15 and macCatalyst 12. That `OWOneCallExample` works well for me. 

I am now getting some problems with the `YAWA` app. I'm investigating...

To resolve my issue with the `YAWA` app, I had to remove and then re-install the `OWOneCall` from the package dependencies, from the `master` branch, or version `1.3.0`.
I also had to remove the `Charts` dependency and re-install it with the `Exact` version `3.6.0`.
To ensure the packages are reloaded,  do: Xcode->File->Packages->Reset package caches.

Note: you may need to clean Xcode with: 
Xcode->Preferences->Locations->Derived Data, click on the small arrow `->` and trash the DerivedData folder.
Shut down Xcode, then re-open it.

**Comment by kwalkerk** [comment]
I followed your suggestions and your app runs properly, and so does mine.

I'm on macOS 11.65 Xcode 13.2.1 targeting iOS 15 and macCatalyst 12.

I also had to remove the dependency that came with with download

Thanks!

**Comment by kwalkerk** [comment]
In my app I have an issue when trying to iterate through items in hourly.

The statement:
```
ForEach(weather.hourly!.prefix(8), id: \.self) { hourly in
....
}
```
gives the following error:
Generic struct 'ForEach' requires that 'Hourly' conform to 'Hashable'

I have a similar statement to iterate through the daily items and do not get that error.  Haven't test yet on alerts

**Comment by workingDog** [comment]
`Hourly` is now `Identifiable`, so you can remove the `id: \.self` from the `ForEach`, try using 
`ForEach(weather.hourly!.prefix(8)) {...}`. `Daily` is both `Identifiable` and `Hashable`, so you could also remove the `id: \.self` from that loop. `OWAlert` is just `Identifiable`.

**Comment by kwalkerk** [comment]
While that compiles it does not run properly.  When done that way it does not appear that there are any items in the "array".

For example the code below will not display anything:
`
ForEach(weather.daily!) { daily in
                            VStack{
                                Text(daily.weatherIconName())
                                    .font(.system(size:55,weight:.medium,design: .default))
                                    .foregroundColor(.white)
                                Label("", systemImage: "wind")
                                    .labelStyle(IconOnlyLabelStyle())
                                    .font(.system(size:55,weight:.medium,design: .default))
                                    .foregroundColor(.gray)
                                Text("72F")
                                    .font(.system(size:55,weight:.medium,design: .default))
                                    .foregroundColor(.white)
                                Text("50F")
                                    .font(.system(size:25,weight:.light,design: .default))
                                    .foregroundColor(.white)
                                Text("38%")
                                    .font(.system(size:25,weight:.light,design: .default))
                                    .foregroundColor(.white)
                            }
                            .border(Color.orange,width:2)
                        }
`

**Comment by workingDog** [comment]
I've copy and pasted your code into `OWOneExample` and all works well for me. I only changed 
`.foregroundColor(.white)` to `.foregroundColor(.green)` because my background is white.
Note, what you probably wanted to do is: `Label("", systemImage: daily.weatherIconName())`,  
to give you the icon from the `weatherIconName`.

Having said that, I had another look at the function `weatherIconName` in `Daily`.
Since `weather` in `Daily` is an array of `Weather`, I return the icon name of first `Weather`, 
which is probably fine for most purpose. I am working on the next version of `weatherIconName` 
that will take an index as its parameter and return the icon name for the chosen index of the weather array.

Note that currently, there are only a small number of icons implemented.

**Comment by workingDog** [comment]
updated `OWOneCall` (master) with improved icon names.

**Comment by kwalkerk** [comment]
I was able to get the new package without issues, but I still can't compile.  Here's a pic of the offending line:
<img width="701" alt="Screen Shot 2022-04-06 at 10 02 26 AM" src="https://user-images.githubusercontent.com/488547/161995296-be8427e7-98ca-4f39-bcd2-b8603faa203d.png">

I do have this line:
let weatherProvider = OWProvider(apiKey: (secret key))

**Comment by workingDog** [comment]
It is not clear from your comment if you are using just the `OWOneCallExample`  or your own code. Your error seems to indicate that the `OWOneCall` package is missing.
Make sure you delete the previous `OWOneCall` dependency, clear the `Xcode->File->Packages->Reset package caches`. Exit Xcode, then re-load the `OWOneCall` from the `master` branch.

Could you try this simple example to track down your issue:

```
import SwiftUI
import OWOneCall

@main
struct TestApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    let weatherProvider = OWProvider(apiKey: "your-key")
    @State var weather = OWResponse()
    
    var body: some View {
        VStack  {
            Text(formattedDate(utc: weather.current?.dt ?? 0))
            Text(weather.current?.weatherInfo() ?? "")
            if let img = weather.current?.weatherIconName() {
                Image(systemName: img.isEmpty ? "smiley" : img)
                    .resizable()
                    .frame(width: 70, height: 65)
                    .foregroundColor(Color.green)
            }
        }.onAppear {
            let myOptions = OWOptions(excludeMode: [.minutely], units: .imperial, lang: "en")
            weatherProvider.getWeather(lat: 30.439619, lon: -84.281997,
                                       weather: $weather,
                                       options: myOptions)
        }
    }
    
    func formattedDate(utc: Int) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        return dateFormatter.string(from: Date(timeIntervalSince1970: TimeInterval(utc)))
    }
}
```

How did you solve your previous issue with your `ForEach(weather.daily!) {...}`? What was the problem?

**Comment by kwalkerk** [comment]
Started new project
Put your code in ContentView
Did as you instructed for Xcode and package dependencies
Quit Xcode
Added your package

Get this message
<img width="272" alt="Screen Shot 2022-04-06 at 8 24 42 PM" src="https://user-images.githubusercontent.com/488547/162096604-12daf5f9-9d77-4f41-9a37-a91738beead5.png">


As for how I fixed it before, I loaded all the source directly into my project, marked hourly as Hashable.  Then it worked

**Comment by workingDog** [comment]
Maybe it is to do with using the older macOS 11.65. I only have macos 12, so I cannot test `OWOneCall` on macOS 11.65. The error you show does not seem to be related to the code of `OWOneCall`. I'll keep investigating. Just to be clear, if you use `OWOneCallExample` downloaded from my repo, it does not work for you, is that correct?

To further track down your issues, how did you solve your previous issue with your `ForEach(weather.daily!) {...}`? What was the problem?

 Regarding the `Hashable` problem, did you try `ForEach(weather.hourly!.prefix(8)) {...} `  ?
 What error did you get?

**Comment by kwalkerk** [comment]
Downloading OWOneCallExample and following your instructions. When I try to add OWOneCall I get the following:
<img width="1022" alt="Screen Shot 2022-04-07 at 9 52 57 AM" src="https://user-images.githubusercontent.com/488547/162216161-be173bf6-667a-4538-afb3-c247f3069b29.png">

I was never able to solve `the ForEach(weather.daily!) {...}? ` problem.  I could get the program to run but there was never any data returned

Hashable problem:  

I'm getting:
<img width="701" alt="Screen Shot 2022-04-06 at 10 02 26 AM" src="https://user-images.githubusercontent.com/488547/162218827-e66e370b-adbd-4a6b-b40d-5ec905cd191d.png">

I'm actually away from home and my primary Mac.  Using a laptop with Big Sur(max for this machine).  I starting to think you're correct about OS version.  Won't be home till sometime next week(in South Florida with my new grandson :))

I'll start again when I get back.

Thanks so much for sticking with me on this!

Kenny

**Comment by kwalkerk** [comment]
I gave it one more try.  Started from a completely new project, added the OneCall package.

And it worked!

The only thing I changed was moving the code which loads the data directly into the .onAppear block for the view.  Now I'm getting all the data even when `ForEach(weather.hourly!.prefix(8)) {...}`

Only thing I haven't tried is the alerts, but it's late here and I'll wait till tomorrow to find a location that has active alerts and will let you know

**Comment by workingDog** [comment]
Glad it is finally working for you. 

Note, I have updated `OWOneCall` `master`.
Of significance for you, I removed the `Hashable` from `Daily`, so you will need to adjust 
any `ForEach` with `ForEach(weather.daily!)`, no `id: \.self` required.

I recommend you use the latest `OWOneCall` `master`.

**Comment by kwalkerk** [comment]
Thanks, will do.

Tested alerts this am, and they worked fine.

Again, thanks for a great package and for all your help.  If you ever need a reference, just let me know.

**Comment by workingDog** [comment]
Thanks for the offer of a reference. If you are going home with your grandson, you are probably a `lot` younger than me.

**Comment by kwalkerk** [comment]
I'm 72 so he odds of me being younger that you are slim :)

**Comment by workingDog** [comment]
You're right, I'm just a bit behind you. If all good, I'll close this issue.

**Comment by kwalkerk** [comment]
All good! 

Thanks!
